---
title: 'Assignment 2: Bootstrapping'
author: "Brad Anderson"
date: "February 23, 2018"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Packages.
```{r, inlcude=FALSE}

library(tidyverse)
library(boot)
library(nlstools)

```

Create survey data vector and proportion function, then bootstrap.
```{r}

survey <- rep(1:0, c(22,14))

prop_fun <- function (x, i) {sum(x[i])/length(x[i])}

boot_10000 <- boot(survey, prop_fun, R = 10000)
boot_10000


```

```{r}
 hist(boot_10000$t,
      main="Histogram for UCSB Survey Bootstrap", 
     xlab="Percent that Experienced Negative Behavior", 
     border="white", 
     col="gray")
```

```{r}

survey_ci <- boot.ci(boot_10000, conf = 0.95, type = "perc")
survey_ci

```

The mean percent of genderqueer students who responded that they had personally experienced “exclusionary, offensive, hostile or intimidating conduct” 	is 61%	(n	=36),	with	a	bootstrapped	95%	confidence	interval	of	[0.44,	0.7778]	 tons	(10,000	 bootstrap	samples).	