---
title: "2c pests"
author: "Brad Anderson"
date: "February 23, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)

```


```{r, message=FALSE}

pest <- read_csv("ca_pest.csv")

pop <- read_csv("ca_pop.csv")

```

```{r, message=FALSE}

both <- merge(pest, pop, by = "County")

both$PestConcentration <- both$PestConcentration <- both$PestPounds/both$CountyArea
  
both <- both %>% 
    select(County, PestConcentration, MedFamilyIncome, Population) %>%
    arrange(-PestConcentration)

```

```{r, message==FALSE}

ggplot( both, aes(x = MedFamilyIncome, y = PestConcentration)) +
  geom_jitter(aes(size = Population))+
  ylab("Pesticide (Pounds per Square Mile)")+
  xlab("Median Family Income")+
  geom_smooth(se = FALSE, method = "lm")+
  theme_bw()+
    theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())+
  ggsave("pesticide.png", dpi = 300, width = 6, height = 4, units = "in")

```
